---
permalink: install/concept_dependency_between_zone_and_host_group_definitions.html 
sidebar: sidebar 
keywords: dependency, between, zone, host, group, definitions, common, errors, cascading, effect 
summary: ゾーン定義でエラーが発生すると、ホストグループ定義の再設定が必要になる場合があります。逆の場合も同様です。 
---
= ゾーン定義とホスト グループ定義間の依存関係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ゾーン定義でエラーが発生すると、ホストグループ定義の再設定が必要になる場合があります。逆の場合も同様です。

ゾーン定義を構成する際には、ONTAPシステム上のFCイニシエータポートのWWPNと、そのゾーンのストレージアレイポートのWWPNまたはWWNNの2つのポートを指定します。同様に、ストレージアレイでONTAPシステムのホストグループを設定する場合は、ホストグループのメンバーにするFCイニシエータポートのWWPNを指定します。

設定の一般的な順序は次のとおりです。

. ゾーン定義を作成します。
. ストレージアレイでホストグループを構成します（リストからONTAPシステム上のFCイニシエータポートのWWPNを選択します）。
. アレイLUNをポートに提供します。


ただし、ゾーン定義の前にホストグループが設定されている場合があるため、ストレージアレイのホストグループ構成にWWPNを手動で入力する必要があります。



== 一般的なエラー

ONTAPの出力では、ONTAPシステム上のFCイニシエータポートはアダプタ番号（0a、0b、0c、0dなど）で識別されます。 オンボードポートを搭載したモデルの場合も同様です。WWPNはスイッチのGUIとストレージアレイのGUIに表示されます。WWPNは16進形式で長いため、次のエラーが発生します。

[cols="2*"]
|===
| WWPNの指定方法 | 一般的なエラー 


 a| 
管理者がWWPNを入力
 a| 
タイプミスが発生します。



 a| 
WWPNはスイッチによって自動的に検出される
 a| 
選択リストからFCイニシエータポートの間違ったWWPNが選択された。

|===
[NOTE]
====
ONTAPシステム、スイッチ、およびストレージアレイが相互に接続されている場合は、ONTAPシステムとストレージアレイポートのWWPNがスイッチで自動的に検出されます。これで、スイッチGUIの選択リストにWWPNが表示され、ゾーンの各メンバーのWWPNを入力するのではなく選択できるようになります。入力ミスを防ぐために、スイッチでWWPNを検出することを推奨します。

====


== エラーの連鎖的影響

ファブリック接続構成の問題をトラブルシューティングする際の最初の手順は、ゾーニングが正しく設定されているかどうかを確認することです。ホストグループ定義とゾーン定義の関係を考慮することも重要です。問題を解決するには、設定プロセス中にエラーが発生した場所によっては、ゾーン定義とホストグループ定義の両方を再設定する必要があります。

スイッチでWWPNを自動検出し、ゾーン定義を先に設定すると、ストレージアレイ上のLUNへのアクセスに使用するFCイニシエータポートのWWPNが、ストレージアレイGUIのホストグループ構成の選択リストに自動的に反映されます。そのため、ゾーニングエラーはストレージアレイのホストグループ選択リストにも反映されます。選択リストには、ONTAPシステムに表示される短いFCイニシエータポートラベル（0a、0bなど）ではなく、16進形式の長いWWPNが表示されます。そのため、想定していたWWPNが表示されていないことは簡単にはわかりません。

次の表に、特定のエラーの影響を示します。

[cols="3*"]
|===
| スイッチのゾーン定義 | ストレージアレイでのホストグループ構成 | ONTAP出力の症状 


 a| 
ゾーン定義に含まれるFCイニシエータポートが正しくありません。その結果、FCイニシエータポートの間違ったWWPNがホストグループ構成に反映されました。
 a| 
選択リストに表示されたFCイニシエータポートのWWPNを選択したが、想定していたWWPNではない。
 a| 
想定されるFCイニシエータポートでアレイLUNが認識されない。



 a| 
正しいFCイニシエータポートがゾーン定義に含まれている。
 a| 
次のいずれかが原因で、ホストグループ定義に間違ったWWPNが含まれています。

* 間違ったWWPNを選択した。
* ゾーン定義を設定する前にホストグループを手動で設定し、FCイニシエータポートのWWPNを入力したときにタイプエラーが発生した。

 a| 

|===