---
permalink: install/concept_example_of_cascading_zoning_and_host_group_configuration_errors.html 
sidebar: sidebar 
keywords: example, cascade, zone, host, group, configuration, errors, troubleshoot 
summary: ゾーン定義でエラーが発生すると、ホストグループ定義に影響する可能性があります。逆も同様です。パスでLUNが認識されない場合は、ゾーニングとホストグループの両方の構成エラーを確認する必要があります。 
---
= ゾーニング構成エラーとホストグループ構成エラーのカスケード例
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ゾーン定義でエラーが発生すると、ホストグループ定義に影響する可能性があります。逆も同様です。パスでLUNが認識されない場合は、ゾーニングとホストグループの両方の構成エラーを確認する必要があります。

設定の順序を次のようにします。

. ゾーン定義がスイッチ上に作成されました。
+
ONTAPシステムのFCイニシエータポート0aのWWPNをゾーン定義に追加しました。ただし、FCイニシエータポート0cのWWPNをゾーン定義に追加する予定でした。

. ストレージアレイにホストグループが作成されました。
+
FCイニシエータポート0aのWWPNを選択しました（選択可能な唯一のWWPNであり、0cではなく0aのWWPNであることが明らかではなかったため）。

. ONTAPで、FCイニシエータポート経由でアレイLUNを表示しました。想定していたポートは0cです。
+
ただし、ゾーン定義とホストグループ定義の両方にFCイニシエータポート0aのWWPNが誤って含まれているため、0c経由のアレイLUNは表示されませんでした。

+
[NOTE]
====
コマンドを使用して、アレイLUNの情報を表示しました `storage array config show` 。

====
. 想定していたイニシエータ経由のLUNが表示されないため、トラブルシューティングを開始します。


ゾーニングとホストグループの両方の設定を確認する必要がありますが、次のどの手順から始めるかは重要ではありません。ホストグループの修正を先に開始するかゾーニングの修正を先に開始するかによって、異なるメッセージが表示されることがあります。



== ゾーニングを先に確認することによるトラブルシューティング

. ONTAPシステムのゾーン定義を確認します。
+
FCイニシエータポート0aのWWPNを含むゾーンが2つあり、0cのWWPNを含むゾーンがないことがわかります。

. 間違ったゾーン定義を修正し、アクティブ化します。
+
[NOTE]
====
を実行している場合、イニシエータポート経由のアレイLUNは表示されませ `storage array config show`ん。

====
. アレイに移動し、FCイニシエータポート0cのWWPNを追加してホストグループを再設定します。
+
これで0cのWWPNがゾーン定義に追加され、アクティブ化されたため、ストレージアレイのホストグループ構成の選択リストに0cのWWPNが表示されます。

. ONTAPシステムでを実行して `storage array config show` FCイニシエータポート経由のアレイLUNが0c経由で表示されていることを確認します。




== ホストグループを先に確認することによるトラブルシューティング

. ONTAPシステムのコンソールからを実行し、 `storage show adapteradapter#``見つからないアダプタのWWPN（この例では-0c）を書き留めます。
. ストレージアレイに移動し、メモしたWWPNとホストグループの選択リストに表示されたWWPNを比較して、想定していたFCイニシエータポートのWWPNが表示されているかどうかを確認します。
+
想定していたWWPNが表示されない場合は、想定していたイニシエータがゾーン定義に含まれていません。

. ストレージアレイでホストグループ内のWWPNを変更できる場合は、表示されているWWPNをメモしたWWPNに変更します。
+
[NOTE]
====
ストレージアレイでホストグループ内のWWPNを変更できない場合は、ゾーン定義の変更後にホストグループ定義を変更する必要があります。

====
+
ゾーニングはまだ修正されていないため、想定していたイニシエータ経由のLUNは表示されません。

. スイッチに移動し、間違ったWWPNを正しいFCポートイニシエータに置き換え、ゾーン定義をアクティブ化します。
. 前の手順でホストグループ定義のWWPNを修正できなかった場合は、ストレージアレイに移動してホストグループを再設定し、FCイニシエータポート0cのWWPNを追加します。
+
これで0cのWWPNがゾーン定義に追加され、アクティブ化されたため、ストレージアレイのホストグループ構成の選択リストに0cのWWPNが表示されます。

. ONTAPシステムでを実行して `storage array config show` FCイニシエータポート経由のアレイLUNが0c経由で表示されていることを確認します。
+
これで、FCイニシエータポート経由でLUNにアクセスできるようになります。


