---
permalink: install/concept_how_the_checksum_type_is_determined_for_aggregates_with_array_luns.html 
sidebar: sidebar 
keywords: how, checksum, type, determined, array, lun, aggregates 
summary: ONTAPアグリゲートには、それぞれチェックサム方式が関連付けられます。アグリゲートのチェックサム方式は、アグリゲートに追加されたアレイLUNのチェックサム方式によって決まります。 
---
= アレイLUNアグリゲートのチェックサム方式の決定方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPアグリゲートには、それぞれチェックサム方式が関連付けられます。アグリゲートのチェックサム方式は、アグリゲートに追加されたアレイLUNのチェックサム方式によって決まります。

アグリゲートのチェックサム方式は、そのアグリゲートに最初に追加されたアレイLUNのチェックサム方式によって決まります。チェックサム方式は、アグリゲート全体（アグリゲート内のすべてのボリューム）に適用されます。アグリゲートにチェックサム方式が異なるアレイLUNを混在させることはできません。

* ブロックチェックサム方式のアグリゲートでは、_block_タイプのアレイLUNを使用する必要があります。
* アドバンスドゾーンチェックサム（AZCSまたはadvanced_zoned）方式のアグリゲートでは、_zoned_タイプのアレイLUNを使用する必要があります。


アグリゲートにアレイLUNを追加する前に、追加するLUNのチェックサム方式を確認しておく必要があります。その理由は次のとおりです。

* チェックサム方式が異なるアレイLUNを同じアグリゲートに追加することはできません。
* アグリゲートを別のチェックサム方式に変換することはできません。


アグリゲートを作成するときに、追加するアレイLUNの数を指定することも、追加するLUNの名前を指定することもできます。アグリゲートに追加するアレイLUNの数を指定する場合は、同じチェックサム方式のアレイLUNが使用可能である必要があります。
