---
permalink: install/concept_available_lun_security_methods.html 
sidebar: sidebar 
keywords: available, lun, security, methods, port-level, storage, array, dedicate, ontap 
summary: さまざまなLUNセキュリティ方式を使用して、特定のアレイLUNにアクセスできるホストを指定できます。ポートレベルのセキュリティ製品やLUNセキュリティ製品を使用することも、ストレージをONTAPシステム専用にすることもできます。 
---
= 使用可能なLUNセキュリティ方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
さまざまなLUNセキュリティ方式を使用して、特定のアレイLUNにアクセスできるホストを指定できます。ポートレベルのセキュリティ製品やLUNセキュリティ製品を使用することも、ストレージをONTAPシステム専用にすることもできます。



== ポートレベルのセキュリティ

ポートレベルのセキュリティを使用すると、特定のホストにのみアレイLUNを提供できます。そのポートは、そのホスト専用になります。

ポートレベルのセキュリティは、すべてのストレージアレイでサポートされるわけではありません。一部のストレージアレイでは、すべてのポートのすべてのLUNがデフォルトで提供され、LUNの表示を特定のホストに制限することはできません。これらのアレイでは、LUNセキュリティ製品を使用するか、ストレージアレイをONTAPシステム専用にする必要があります。ポートレベルのセキュリティがストレージアレイでサポートされているかどうかを確認するには、ストレージアレイのドキュメントを参照してください。



== LUNセキュリティ製品

LUNセキュリティ製品を使用すると、同じポートにゾーニングされたホストを制御して、ホストがそのポート経由で特定のアレイLUNにのみアクセスできるようにすることができます。これにより、アレイLUNを他のホストからマスキングすることで、他のホストが同じアレイLUNにアクセスできなくなります。



== ストレージアレイをONTAP専用にする

ストレージアレイをONTAPシステム専用にすることができます。この場合、ONTAPシステム以外のホストはストレージアレイに接続されません。

ONTAPシステムの保護と冗長性を強化するには、ゾーニングとLUNセキュリティの両方を使用する必要があります。

LUNセキュリティ方式に加えて、ベンダーのストレージアレイに対応するLUNセキュリティに関するその他の詳細も確認する必要があります。一部のストレージアレイは、ONTAPシステム専用にする必要があります。

* 関連情報 *

https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["サードパーティ製ストレージ向けのFlexArray仮想化の実装"]

https://docs.netapp.com/us-en/ontap-flexarray/implement-e-series/index.html["NetApp E-Seriesストレージ向けのFlexArray仮想化の実装"]
