---
permalink: install/concept_stages_of_implementation_for_a_system_using_array_luns.html 
sidebar: sidebar 
keywords: stages, implementation, system, use, array, luns, back end, front end 
summary: ストレージアレイのLUNを使用するシステム構成の実装には、バックエンド実装とフロントエンド実装の2つの段階があります。各ステージのタスクの概要を理解しておくと、構成を計画する際に役立ちます。 
---
= アレイLUNを使用するシステムの実装段階
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイのLUNを使用するシステム構成の実装には、バックエンド実装とフロントエンド実装の2つの段階があります。各ステージのタスクの概要を理解しておくと、構成を計画する際に役立ちます。



== ステージ1：バックエンド実装

バックエンド実装のセットアップには、ストレージアレイを使用するONTAPシステムのセットアップに必要なすべてのタスク（ONTAPソフトウェアのインストールまで）が含まれます。

バックエンド実装をセットアップするタスクは次のとおりです。

. アレイLUNの作成とフォーマット
. ポートの割り当て
. ケーブル接続
. スイッチのゾーニング（該当する場合）
. ONTAPで、ONTAPシステムへの特定のアレイLUNの割り当て
. ONTAPで、ネットワークにONTAPシステムをセットアップするための情報を指定する
. ONTAPソフトウェアのインストール


ディスクシェルフと一緒に購入したONTAPシステムは、ONTAPソフトウェアがインストールされた状態で出荷されます。このような構成では、ルートボリュームを作成したり、ライセンスとONTAPソフトウェアをインストールしたりする必要はありません。

ONTAPシステムをディスクシェルフと一緒に購入しなかった場合は、クラスタをセットアップする前にONTAPを設定する必要があります。



== ステージ2：フロントエンド実装

フロントエンド実装をセットアップするタスクは、ディスクを使用するシステムの場合と同じです。たとえば、次のようなタスクがあります。

* すべてのプロトコル（NAS、FC、またはその両方）に対するONTAPシステムの設定
* SnapVault、SnapMirror、SnapValidator、SnapshotコピーなどのONTAP機能の設定
* ボリュームとアグリゲートの作成
* データ保護の設定（テープへのNDMPダンプを含む）

