---
permalink: install/concept_rules_for_sharing_an_fc_initiator_port_with_multiple_target_ports.html 
sidebar: sidebar 
keywords: rules, share, fc initiator, port, multiple, target, connect, storage, arrays 
summary: ONTAPシステムのFCイニシエータポートは、別 々 のストレージアレイにある最大4つのターゲットポートに接続できます。FCイニシエータポートを複数のターゲットで共有すると、使用するFCイニシエータポートの数を最小限に抑えたい場合に便利です。 
---
= 複数のターゲット ポートでFCイニシエータ ポートを共有する際のルール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPシステムのFCイニシエータポートは、_separate_storageアレイ上の最大4つのターゲットポートに接続できます。FCイニシエータポートを複数のターゲットで共有すると、使用するFCイニシエータポートの数を最小限に抑えたい場合に便利です。

また、アクセスするターゲットポートに基づいてFCイニシエータに異なる論理デバイスのセットを提供できる場合は、FCイニシエータポートを_same_storageアレイ上の最大4つのターゲットポートに接続することもできます。

1つのFCイニシエータポート経由で認識できるアレイLUNの数には制限があります。これらの制限はリリースによって異なります。



== _separate_storage arraysの複数のターゲットポートにFCイニシエータポートを接続する場合のルール

この構成でのルールは次のとおりです。

* すべてのストレージアレイが同じベンダーモデルファミリーに属している必要があります。
+
パフォーマンスとフェイルオーバーの仕様が共通する、ストレージ アレイの分類。たとえば、同じファミリーのメンバーは、すべてアクティブ/アクティブフェイルオーバーを実行するか、またはすべてアクティブ/パッシブフェイルオーバーを実行します。ストレージアレイファミリーを決定するには、複数の要因が使用される場合があります。たとえば、アーキテクチャが異なるストレージ アレイは、他の特徴が同じでも別のファミリーになります。

* MetroCluster構成では、単一のFCイニシエータポートを複数のターゲットポートに接続できます。
* 1つのFCイニシエータポートを、複数のストレージアレイの最大4つのターゲットポートに接続できます。
* 同じFCイニシエータポートから複数のターゲットポートにアクセスする場合でも、FCイニシエータとターゲットポートの各ペアを別 々 のゾーンに1対1で配置する必要があります。




== _same_storage array上の複数のターゲットポートにFCイニシエータポートを接続する場合のルール

この構成は、LUNマスキング、提供、またはホストグループ機能を使用して、アクセスするターゲットポートに基づいて同じFCイニシエータに異なるLUNグループを提供できるストレージアレイでのみ使用できます。

一部のストレージアレイでは、アクセスするターゲットポートに基づいて異なる論理デバイスのセットを1つのFCイニシエータに提供できます。このタイプのストレージアレイでは、同じFCイニシエータを複数のホストグループに含めることができます。この機能を搭載したストレージアレイでは、各FCイニシエータポートが同じストレージアレイの複数のターゲットポートにアクセスでき、各ターゲットポートがFCイニシエータに異なるLUNグループを提供します。使用しているストレージアレイで同じFCイニシエータを複数のホストグループに含めることができるかどうかを確認するには、ストレージアレイのドキュメントを参照してください。

この構成のルールは次のとおりです。

* 単一のFCイニシエータポートをストレージアレイ上の最大4つのターゲットポートに接続できます。
* MetroCluster構成では、単一のFCイニシエータポートを複数のターゲットポートに接続できます。
* 同じFCイニシエータから複数のターゲットポートにアクセスする場合でも、FCイニシエータとターゲットポートの各ペアを別 々 のゾーンに1対1で配置する必要があります。


* 関連情報 *

https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["サードパーティ製ストレージ向けのFlexArray仮想化の実装"]

https://docs.netapp.com/us-en/ontap-flexarray/implement-e-series/index.html["NetApp E-Seriesストレージ向けのFlexArray仮想化の実装"]

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["ファブリック接続MetroClusterのインストールと設定"]
