---
permalink: install/concept_planning_summary_for_a_v_series_system_using_native_disks.html 
sidebar: sidebar 
keywords: plan, summary, v-series, system, native, disks, additional, considerations, setup, array, luns 
summary: ネイティブディスクシェルフは、新規または既存のVシリーズシステムに設置できます。ただし、ネイティブディスクシェルフをVシリーズシステムに設置する場合は、FASシステムに設置する場合と比較して、いくつかの追加要素を考慮する必要があります。 
---
= ネイティブディスクを使用するVシリーズシステムの計画概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネイティブディスクシェルフは、新規または既存のVシリーズシステムに設置できます。ただし、ネイティブディスクシェルフをVシリーズシステムに設置する場合は、FASシステムに設置する場合と比較して、いくつかの追加要素を考慮する必要があります。



== ディスクを使用するVシリーズシステムの基本的なセットアップの計画に関するその他の考慮事項

ネイティブディスクを使用するVシリーズシステムの基本的なセットアップとインストールの要件を決定する際には、次の点を考慮する必要があります。

* ディスクシェルフと一緒に購入したVシリーズシステムは、出荷時点でルートボリュームが設定され、ライセンスとONTAPソフトウェアがインストールされています（FASシステムの場合と同様）。
* Vシリーズシステムをディスクシェルフと一緒に購入しなかった場合は、ONTAPソフトウェアと該当するライセンスをインストールする必要があります。
* ONTAPは、Vシリーズシステムに接続されているネイティブディスクに自動的に所有権を割り当てます。




== VシリーズシステムでディスクとアレイLUNの両方を使用する場合の計画に関する追加の考慮事項

次の表は、計画に関するその他の考慮事項と、各タスクに役立つ情報の参照先をまとめたものです。

|===
| 計画に関する考慮事項 | ガイドラインの参照先 


 a| 
ルート ボリュームの場所
 a| 
xref:concept_location_of_the_root_volume.adoc[ルート ボリュームの場所]



 a| 
Vシリーズシステムでサポートされる最大数の範囲内で割り当てることができるディスクとアレイLUNの合計数
 a| 
https://hwu.netapp.com["NetApp Hardware Universe"]



 a| 
FCイニシエータポートの用途
 a| 
xref:concept_requirements_for_v_series_fc_initiator_port_usage.adoc[FCイニシエータ ポートの用途別要件]



 a| 
ディスクに格納するデータのタイプとアレイLUNに格納するデータのタイプ
 a| 
管理が必要なデータの種類を評価し、ネイティブディスクまたはアレイLUNのどちらにデータを格納できるかを決定する必要があります。

|===