---
permalink: install/concept_formulas_for_calculating_array_lun_size_considering_checksum_type.html 
sidebar: sidebar 
keywords: formulas, calculate, array, lun, size, checksum, type, usable, capacity, snapshot, reserve, maximum 
summary: アレイLUNの使用可能容量は、チェックサム方式などのいくつかの要素によって左右されます。あるサイズのアレイLUNで使用可能な容量、または目的のストレージ容量を提供するために必要なアレイLUNのサイズは、式を使用して計算できます。 
---
= チェックサム方式に基づくアレイLUNサイズの計算式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アレイLUNの使用可能容量は、チェックサム方式などのいくつかの要素によって左右されます。あるサイズのアレイLUNで使用可能な容量、または目的のストレージ容量を提供するために必要なアレイLUNのサイズは、式を使用して計算できます。

使用可能容量_を確保するために必要なアレイLUNのサイズは、チェックサム方式などのいくつかの要素によって左右されます。使用可能な容量は、ストレージに使用可能なスペースの量です。

次の表に、必要なアレイLUNサイズの計算方法を示します。

[cols="2*"]
|===
| 知っていること | 確認する項目 


 a| 
アレイLUNのサイズ
 a| 
ストレージに使用可能な容量（使用可能な容量）。すべての要素に必要なスペースの量を考慮する必要があります。



 a| 
アレイLUNに必要なストレージ容量
 a| 
必要なアレイLUNのサイズ。必要なストレージ容量と他の要素に必要なスペースを考慮する必要があります。

|===
[NOTE]
====
これらの式の2TBは2TiB（2199023255552バイト）を表し、ONTAPによる測定値の計算方法では2097.152GnaBまたは2.097TnaBになります。

====


== 使用可能容量の計算式

アレイLUNのサイズがわかっている場合は、次の式を使用して、アレイLUNでストレージに使用可能な容量を判断できます。この式では、Snapshotリザーブを考慮しています。

* Yはストレージに使用可能な容量です。
* NはアレイLUNの合計容量です。


[cols="2*"]
|===
| チェックサム方式 | 計算式 


 a| 
bcs --アレイLUN < 2TB
 a| 
N x｛0.875 x 0.9 x 0.99 x（1 - Snapshotリザーブ）｝= Y



 a| 
bcs --アレイLUN≧2TB以上
 a| 
N x｛0.875 x 0.9 x 0.998 x（1 - Snapshotリザーブ）｝= Y



 a| 
AZCS --アレイLUN < 2TB
 a| 
N x｛0.984 x 0.9 x 0.99 x（1 - Snapshotリザーブ）｝= Y



 a| 
AZCS --アレイLUN≧2TB以上
 a| 
N x｛0.984 x 0.9 x 0.998 x（1 - Snapshotリザーブ）｝= Y

|===


== 例1：Snapshotリザーブの有無による計算

次の例では、アレイLUNの合計容量は4GBで、ボリュームのSnapshotリザーブはData ONTAP 8.1.1のデフォルト（5%）に設定されています。

次の例は、2TB未満のアレイLUNを示しています。

[cols="2*"]
|===
| チェックサム方式 | 計算式 


 a| 
BCS（アレイLUN < 2TB）
 a| 
4 x｛0.875 x 0.9 x 0.99 x 0.95｝= 2.96GB（ストレージに使用可能なスペース）



 a| 
AZCS（アレイLUN < 2TB）
 a| 
4 x｛0.984 x 0.9 x 0.99 x 0.95｝= 3.33GB（ストレージに使用可能なスペース）

|===


== 必要な最大アレイLUNサイズの計算式

目的のストレージ容量を確保するために必要なアレイLUNの容量がわかっている場合は、次の計算式を使用して、LUNのスペースを必要とする要素を考慮し、必要なアレイLUNの合計サイズを算出できます。

* Yは、必要なアレイLUNの正確なスペース量です。
* Snapshotコピーを使用する場合は、Snapshotリザーブが考慮されます。


次の例は、2TB未満のアレイLUNを示しています。

[cols="2*"]
|===
| チェックサム方式 | 計算式 


 a| 
BCS（アレイLUN < 2TB）
 a| 
Y÷｛0.875 x 0.9 x 0.99 x（1 - Snapshotリザーブ）｝=実際に必要な容量



 a| 
AZCS（アレイLUN < 2TB）
 a| 
Y÷｛0.984 x 0.9 x 0.99 x（1 - Snapshotリザーブ）｝=実際に必要な容量

|===


== 例2：Snapshotリザーブの有無による計算

この例では、ボリュームのSnapshotリザーブがData ONTAP 8.1.1のデフォルト設定（5%）です。

次の例は、2TB未満のアレイLUNを示しています。

[cols="2*"]
|===
| チェックサム方式 | 計算式 


 a| 
BCS（アレイLUN < 2TB）
 a| 
10GB÷｛0.875 x 0.9 x 0.99 x 0.95｝=13.5GB（実際に必要な容量）



 a| 
AZCS（アレイLUN < 2TB）
 a| 
10GB÷｛0.984 x 0.9 x 0.99 x 0.95｝=12.05GB（実際に必要な容量）

|===


== 例3：Snapshotリザーブなしの計算

ストレージに使用可能な容量として10GBが必要です。次の例は、Snapshotコピーを使用しない場合のアレイLUNの実際のサイズを計算する方法を示しています。

次の例は、2TB未満のアレイLUNを示しています。

[cols="2*"]
|===
| チェックサム方式 | 計算式 


 a| 
BCS（アレイLUN < 2TB）
 a| 
10GB÷｛0.875 x 0.9 x 0.99｝=12.8GB（実際に必要な容量）



 a| 
AZCS（アレイLUN < 2TB）
 a| 
10GB÷｛0.984 x 0.9 x 0.99｝=11.41GB（実際に必要な容量）

|===