---
permalink: install/concept_requirements_for_connecting_to_storage_arrays.html 
sidebar: sidebar 
keywords: requirements, connect, storage, arrays 
summary: ストレージアレイにONTAPシステムを接続する方法を計画する場合は、冗長性、パス設定、およびその他のガイドラインについてポート間接続の計画で検討する必要があります。 
---
= ストレエシアレイニセツソクスルタメノヨウケン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイにONTAPシステムを接続する方法を計画する場合は、冗長性、パス設定、およびその他のガイドラインについてポート間接続の計画で検討する必要があります。

接続を設定するための要件は次のとおりです。

* ストレージアレイ上の冗長ポートペアの各接続を、ONTAPシステム上の別 々 のFCイニシエータポートに接続する必要があります。
* FCスイッチで使用するポートを冗長にする必要があります。
* SPOFを回避するために接続を設定する必要があります。
+
ある特定のLUNにアクセスするために選択するストレージアレイ上のポートには、単一点障害（Single Point of Failure）を回避するために、別のコンポーネント（代替のコントローラ、クラスタ、エンクロージャなど）が含まれていることを確認してください。これは、1つのコンポーネントで障害が発生してもアレイLUNへのすべてのアクセスが失われないようにするためです。

* パスの数が、お使いのONTAPリリースでサポートされているパスの数を超えることはできません。
* 複数のターゲットポートでFCイニシエータポートを共有する場合や、複数のFCイニシエータポートでターゲットポートを共有する場合は、該当するルールに従う必要があります。
* ストレージアレイでサポートされるポートあたりのホストグループあたりのLUN数が、ONTAPシステムで使用されているLUNの数より少ない場合は、ONTAPシステムとストレージアレイの間にケーブルを追加する必要があります。

