---
permalink: install/reference_commands_for_checking_back_end_configuration.html 
sidebar: sidebar 
keywords: commands, check, back-end, configuration 
summary: ONTAPのいくつかのコマンドは、ストレージアレイの構成に関する情報（バックエンド構成エラーを含む）を提供します。これらのコマンドは、インストールの検証やトラブルシューティングに特に役立ちます。 
---
= バックエンド構成の確認用コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPのいくつかのコマンドは、ストレージアレイの構成に関する情報（バックエンド構成エラーを含む）を提供します。これらのコマンドは、インストールの検証やトラブルシューティングに特に役立ちます。

 `storage array config show`コマンドは、インストールの検証時に最初に使用するコマンドです。また、システムが想定どおりに動作していない場合や、エラーメッセージが表示された場合に使用する最初のコマンドでもあります。

次の表に、インストールの検証とトラブルシューティングに特に役立つコマンドを示します。

|===
| コマンド | 説明 


 a| 
`storage array config show`
 a| 
アレイLUNを使用するONTAPシステム環境でのバックエンドデバイスの構成に関する情報をストレージアレイレベルで提供します。このコマンドは、ストレージアレイとクラスタの接続方法を表示します。アレイLUNを使用するONTAPシステムとストレージアレイの連携に支障をきたす問題がONTAPで検出された場合、 `storage array config show` を実行すると、を実行してエラーの詳細を確認するように指示されます `storage errors show` 。

このコマンドは、構成が意図したとおりに設定されていることを確認する場合にも役立ちます。たとえば、の出力で、想定数のアレイLUNグループが作成されたことを確認できます。



 a| 
`storage array show -name array_name`
 a| 
クラスタに認識されるすべてのストレージアレイ、または指定したストレージアレイに関する情報を表示します。提供されたアレイLUNの数がシステムの容量を超えると、ONTAPで検出できなかったLUNの数が[Error]テキストフィールドに表示されます。特にメモリ不足のシステムでは、この問題に注意する必要があります。



 a| 
`storage path quiesce`
 a| 
特定のパス上の特定のアレイLUNへのI/Oを一時的に中断します。パスは、リブート時またはを実行すると再びアクティブになり `storage path resume`ます。一部のストレージアレイでは、アレイLUNを削除または移動するために一定期間I/Oを停止する必要があります。

[NOTE]
====
 `storage path quiesce`IBM DSストレージアレイではコマンドを使用できません。

====


 a| 
`storage path resume`
 a| 
I/Oフローを再開できます。これは休止の逆です。 `storage path resume`コマンドは、主にハードウェアのメンテナンス時（ケーブルやGBICを取り外す場合など）や、アレイLUNへのパスが誤って休止された場合に使用します。パスの休止後にこのコマンドを実行する必要があるとは限りません。たとえば、新しくマッピングされたアレイLUNをONTAPで検出できます。



 a| 
`storage array show`
 a| 
クラスタで認識されるストレージアレイに関する情報（名前、ベンダー、モデル、 およびフェイルオーバータイプ。



 a| 
`storage disk show`
 a| 
パラメータを指定せずにを入力すると、 `storage disk show` すべてのディスクおよびアレイLUNについて、名前、使用可能なサイズ、コンテナタイプ、位置、アグリゲート、 そして所有者。パラメータとしてディスク名またはアレイLUN名を指定してを入力すると `storage disk show` 、そのディスクまたはアレイLUNの詳細（割り当て済みまたは未割り当て）、所有者、アレイLUNのパスなど）が表示されます。出力は3つのセクション（アレイLUNに関する情報、アレイLUNへのパスに関する情報、およびアレイLUNに関連するエラー）に分かれます。



 a| 
`storage disk show -errors _**_`
 a| 
パラメータを指定してを入力すると、 `storage disk show` ``-errors` ディスクレベルおよびアレイLUNレベルの構成エラーの詳細が表示されます。コマンドの出力はコマンドの出力に似ていますが `storage disk error show` 、に `storage disk show -errors` は、ノード、クラスタ、ベイの位置などのパラメータで出力をフィルタリングするためのオプションが用意されています。



 a| 
`storage disk error show`
 a| 
バックエンド構成エラーの詳細がディスクレベルおよびアレイLUNレベルで表示されます。パラメータとしてアレイLUN名を指定してshowを入力すると `storage disk error` 、指定したアレイLUNに関連する構成エラーの詳細が表示されます。これらのエラーは、ストレージアレイと連携するようにONTAPを設定する前に解決しておく必要があります。



 a| 
`storage errors show`
 a| 
ONTAPシステムとストレージアレイの連携に支障をきたすバックエンド構成エラーの詳細をアレイLUNレベルで表示します。で特定されたエラーは、ストレージアレイに対してONTAPを設定する前に修正する必要があります `storage errors show` 。

[NOTE]
====
 `storage errors show`コマンドでは、ディスク構成エラーに関する情報は提供されません。ディスクとアレイLUNの両方の構成エラーに関する情報を表示するには、コマンドまたはコマンドを使用し `storage disk show -errors` `storage disk error show` ます。

====
|===