---
permalink: install/reference_array_luns_are_configured_with_conflicting_failover_modes_clustered_data_ontap_8_2_and_later.html 
sidebar: sidebar 
keywords: array, luns, configured, conflict, failover, modes 
summary: ONTAPでは、特定のONTAPシステムが認識するアレイLUNは、同じフェイルオーバーモードに設定する必要があります。一部のストレージアレイでは、アレイLUNへのパスごとに異なるフェイルオーバーモードを設定することができます。 
---
= アレイLUN間でフェイルオーバーモードが競合している
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPでは、特定のONTAPシステムが認識するアレイLUNは、同じフェイルオーバーモードに設定する必要があります。一部のストレージアレイでは、アレイLUNへのパスごとに異なるフェイルオーバーモードを設定することができます。



== storage errors showのメッセージ

[listing]
----
NAME(UID): This array LUN is configured with conflicting failover modes. Each path to this LUN must use the same mode.
----


== 説明

EMC CLARiXストレージアレイなど、一部のストレージアレイでは、FCイニシエータポートによってフェイルオーバーモードを設定できます。このようなストレージアレイでは、同じONTAPシステムのFCイニシエータから認識されるアレイLUNに異なるフェイルオーバーモードを設定することができます。ONTAPでは、特定のONTAPシステムからアレイLUNへのパス間でフェイルオーバーモードが異なる構成はサポートされていません。

FCイニシエータによるアレイLUNのフェイルオーバーモードの設定がストレージアレイで許可されている場合は、ONTAPシステムが認識するアレイLUNでフェイルオーバーモードの設定に問題がないことをインストールの検証プロセスで確認する必要があります。 `storage errors show`コマンドでは、アレイLUNに異なるフェイルオーバーモードが設定されているとアラートが表示され、EMSメッセージが生成されます。

アレイLUNのフェイルオーバーモード設定が一貫していなくてもシステムは動作しますが、この問題はできるだけ早く解決する必要があります。そうしないと、パスで障害が発生した場合に、ONTAPシステムが正常に動作しなかったり、フェイルオーバーが実行されなかったり、システムがパニック状態になったりする可能性があります。

[NOTE]
====
ONTAPでは、ONTAPを実行するノード間で、異なるフェイルオーバーモード設定がサポートされます。たとえば、ノードAでアレイLUNへのパスにアクティブ/パッシブモードを使用し、ノードBで同じアレイLUNへのパスにALUAを使用できます。

====


== トラブルシューティングと問題解決

LUNの初期化中にONTAPで検出された最初のパスのフェイルオーバーモードが、ONTAP特定のONTAPシステムのLUNへのすべてのパスのフェイルオーバーモードとみなされます。その後検出されたパスのフェイルオーバーモードが最初のパスのフェイルオーバーモードと一致しない場合、ONTAPはエラーメッセージを表示します。

次の `storage errors show` 例では、ONTAPから、mysystem1のFCイニシエータ0aで認識されるLUN EMC-1.128のフェイルオーバーモードが_proprietary _であり、そのアレイLUNの最初のパスでONTAPが検出したフェイルオーバーモードと異なることがわかります。

[listing]
----

mysystem1::> storage errors show
EMC-1.128 (60060160e1b0220008071baf6046e211): hba 0a port 500601603ce014de mode Proprietary: This array LUN is configured with conflicting failover modes. Each path to this LUN must use the same mode.

Disk: EMC-1.128
UID: 60060160:E1B02200:1C65EB20:BFF7E111:00000000:00000000:00000000:...
----
ストレージアレイでフェイルオーバーの不一致を修正する必要があります。ただし、この問題を修正する手順は、最初のパスでONTAPが検出したフェイルオーバーモードが、ONTAPシステムからアレイLUNへのすべてのパスに使用するフェイルオーバーモードであるかどうかによって異なります。

. と入力します（インストールの検証プロセスで入力していない場合）。 `storage errors show`
+
[NOTE]
====
 `storage array config`修正が必要な問題がある場合は、コマンドを実行するように指示され `storage error show` ます。

====
. の出力を確認して `storage errors show` 、ONTAPの想定と一致しないアレイLUNのフェイルオーバーモード設定を確認します。
+
|===
| 最初のパスで検出されたフェイルオーバーモード | 例 | 必要な処理 


 a| 
必要なもの
 a| 
希望するフェイルオーバーモードはALUAで、ONTAP最初のパスで検出されたフェイルオーバーモードはALUAである
 a| 
エラーメッセージに表示されたイニシエータのフェイルオーバーモードをストレージアレイで変更しONTAPます。手順3に進みます。



 a| 
希望とは異なる
 a| 
希望するフェイルオーバーモードはアクティブ/パッシブだが、ONTAP最初のパスで検出されたフェイルオーバーモードはALUAである
 a| 
アレイLUNがONTAPシステムで認識されないようにします。手順4に進みます。

|===
. イニシエータのフェイルオーバーモードを変更する必要がある場合は、次の手順に従って不一致を修正してください。
+
この手順は、最初のpath_is_で目的のフェイルオーバーモードが検出された場合に使用します。

+
.. ONTAPで、2番目のパスをオフラインにします。
.. エラーメッセージに示されたイニシエータのフェイルオーバーモードをストレージアレイで変更しONTAPます。
.. ONTAPで、2番目のパスをオンラインに戻します。


. 不一致の問題を修正するためにONTAPシステムでアレイLUNが認識されないようにする必要がある場合は、アレイLUNがスペアであるかアグリゲートに含まれているかに応じて、次のいずれかの方法を選択します。
+
最初のパス_で検出されたフェイルオーバーモードが希望どおりでない場合は、これらの方法のいずれかを使用します。

+
|===
| 方法1：アレイLUNがスペア（アグリゲートの一部ではない）である | 方法2：LUNがアグリゲートに含まれている 


 a| 
この方法では、ONTAPシステムをリブートする必要はありません。

.. ONTAPで、該当する各スペアLUNに対して次のコマンドを実行します。 `disk remove_ownership LUNfullname`
.. ストレージアレイで、該当する各アレイLUNをONTAPシステムへのすべてのパスでマスクします。
.. 1分ほど待ってから、アレイLUNがONTAPシステムで認識されなくなったことを確認します。
.. ONTAPシステムの各FCイニシエータに同じフェイルオーバーモードを設定します。
.. 該当するすべてのアレイLUNをONTAPシステムに再度提供します。
+
ONTAPが次回LUN検出を実行するときに、LUNを検出する必要があります。

.. を実行して、 `storage errors show` フェイルオーバーモードのエラーが解消されたことを確認します。

 a| 
この方法では、ONTAPシステムをリブートする必要があります。

.. ONTAPシステムをリブートし、Loaderプロンプトを表示したままにします。
.. ストレージアレイで、このシステムのFCイニシエータのフェイルオーバーモード設定を確認し、必要に応じて目的のフェイルオーバーモードに更新します。
.. ONTAPシステムをリブートします。
.. を実行して、 `storage errors show` フェイルオーバーモードのエラーが解消されたことを確認します。


|===

