---
permalink: install/reference_reasons_for_more_paths_to_an_array_lun_than_expected.html 
sidebar: sidebar 
keywords: reasons, paths, array, lun, expected, output, show, config, issue 
summary: アレイLUNへのパスが予期せず追加される主な原因は、ゾーニングの問題とケーブルの数が多すぎることです。アレイLUNへのパスが3つあることはベストプラクティスではありませんが、この問題を修正する必要はありません。 
---
= アレイLUNへのパスが想定よりも多い理由
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アレイLUNへのパスが予期せず追加される主な原因は、ゾーニングの問題とケーブルの数が多すぎることです。アレイLUNへのパスが3つあることはベストプラクティスではありませんが、この問題を修正する必要はありません。



== storage array config showの出力例

ONTAPシステムのFCイニシエータポートペアは、0aと0cです。次の例では、の出力に余分なパス0bが表示されて `storage array config show` います。

[listing]
----

mysystem1::> storage array config show
             LUN   LUN
Node         Group Count   Array Name       Array Target Port   Initiator
----------   ----- -----  ----------------  ------------------  ----------
mysystem1a    1     3     HITACHI_DF600F_1  50060e80004291c0    0a
                                            50060e80004291c1    0b
                                                                0c

3 entries were displayed.
----
[NOTE]
====
の出力でアレイターゲットポートが表示されていないイ `storage array config show` ニシエータは、その上のイニシエータと同じアレイターゲットポートに接続されています。

====


== 説明

LUNグループ内にパスが3つある場合は、余分なパスがあることを示します。ONTAP構成では、パスを2つまたは4つ使用することを推奨します。

パスが想定よりも多くなる原因には次のようなものがあります。

* 必要以上のケーブルが接続されました。
* ゾーニング設定エラーが原因で余分なパスが発生しました。




== 問題の解決

追加のパスを使用することはベストプラクティスではありませんが、システム面では正しくありません。この問題を修正する必要はありません。意図した構成に合わせて問題を修正するには、次の手順を実行します。

. ケーブル接続とゾーニング設定が原因であることを確認し、余分なパスの原因となっている問題を修正します。
. 問題を修正したら、を再度実行して `storage array config show` 余分なパスがなくなったことを確認します。

