---
permalink: install/reference_the_storage_errors_show_messages_and_their_resolution.html 
sidebar: sidebar 
keywords: storage, errors, show, messages, resolution 
summary: storage errors showにエラー状態が表示された場合は、その原因と修正方法を特定する必要があります。 
---
= storage errors showのメッセージとその解決方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
がエラー状態をフラグするとき `storage errors show` は、エラーが発生した理由とその修正方法を特定する必要があります。

次の表に、で検出されるバックエンド構成エラー `storage errors show` とその原因と解決方法に関する詳細情報の参照先を示します。

|===
| `storage errors show` メッセージ | このメッセージの詳細の参照先 


 a| 
`NAME (Serial #): All paths to this array LUN are connected to the same fault domain. This is a single point of failure``です。
 a| 
xref:reference_all_paths_to_an_array_lun_are_on_the_same_storage_array_controller.adoc[あるアレイLUNへのすべてのパスが同じストレージアレイコントローラにある]



 a| 
`NAME (Serial #), port WWPN1: LUN 1 occurs more than once. LUNs cannot be reused on the same array target port`です。
 a| 
xref:reference_duplicate_lun_ids_on_a_target_port.adoc[ターゲットポートでのLUN IDの重複]



 a| 
`NAME (Serial #): This array LUN is an access control LUN. It is not supported and should be masked off or disabled``です。
 a| 
xref:reference_an_access_control_lun_is_presented_to_ontap.adoc[アクセス制御LUNが提供された]



 a| 
`NAME (Serial #) This array LUN is configured with conflicting failover modes. Each path to this LUN must use the same mode`です。
 a| 
xref:reference_array_luns_are_configured_with_conflicting_failover_modes_clustered_data_ontap_8_2_and_later.adoc[アレイLUN間でフェイルオーバーモードが競合している]



 a| 
`NAME (Serial #): This Array LUN is only available on one path. Proper configuration requires two paths`です。
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[アレイLUNへのパスが複数ない]



 a| 
`NAME (Serial #): This array LUN is too large and is not usable. The maximum array LUN size supported is xTB`です。
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[アレイLUNのサイズが小さすぎる、または大きすぎる]



 a| 
`NAME (Serial #): This array LUN is too small and is not usable. The minimum array LUN size supported is 1GB`です。
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[アレイLUNのサイズが小さすぎる、または大きすぎる]



 a| 
`NAME (Serial #): This Array LUN is using multiple LUN IDs. Only one LUN ID per serial number is supported`です。
 a| 
xref:reference_lun_ids_for_the_same_ldev_do_not_match.adoc[同じLDEVのLUN IDが一致していない]

Volume Set Addressingに一貫性がない



 a| 
`NAME (Serial #): This array LUN is marked foreign and has a reservation`です。
 a| 
xref:reference_array_lun_is_marked_foreign_and_has_a_reservation_data_ontap_8_3_and_later.adoc[アレイLUNがforeignとマークされており、予約されています]

|===