---
permalink: install/reference_terminology_comparison_between_storage_array_vendors.html 
sidebar: sidebar 
keywords: terminology, comparison, between, storage, array, vendors 
summary: ストレージアレイベンダーによって、類似する概念を表す用語が異なる場合があります。逆に、同じ用語の意味はアレイベンダーによって異なる場合があります。 
---
= ストレージアレイベンダーによる用語の比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイベンダーによって、類似する概念を表す用語が異なる場合があります。逆に、同じ用語の意味はアレイベンダーによって異なる場合があります。

次の表に、いくつかの一般的な用語の対応を示します。

|===
| 期間 | ベンダー | 定義 


 a| 
ホストグループ
 a| 
日立
 a| 
ストレージアレイのポートへのホストアクセスを指定できる構成エンティティ。LUNにアクセスするONTAPシステムのFCイニシエータポートのWWNを指定します。このプロセスはベンダーによって異なるほか、同じベンダーでもストレージアレイモデルによって異なる場合があります。



 a| 
HP XP
 a| 



| ストレージグループ  a| 
EMC CX、EMC VNX
 a| 



| ホスト定義  a| 
3PAR
 a| 



| ホスト  a| 
3PAR、HP EVA、HP XP、Hitachi
 a| 



 a| 



| パリティグループ  a| 
Hitachi、HP XP
 a| 
定義されたRAIDレベルを形成するバックエンド内のディスクの配列。



 a| 
RAIDグループ
 a| 
ONTAP、EMC CX、EMC VNX
 a| 



| ディスクグループ  a| 
HP EVA
 a| 
ストレージプールを形成する物理ディスクのセットで、そこから仮想ディスクを作成できます。



 a| 
パリティセット、RAIDセット
 a| 
3PAR
 a| 
parity-protected_chunklets_のグループ。（チャンクレットは、物理ディスク上の256MBの連続したスペースのブロックです）。



 a| 
 a| 
|  


| クラスタ  a| 
ONTAP
 a| 
ONTAPにおいて、複数のノードのリソースを大規模な仮想サーバにプールし、作業をクラスタ全体に分散できるようにするノードのグループ。



 a| 
| Hitachi、HP XP  a| 
ホストの接続先ポートを含むストレージアレイ上のハードウェアコンポーネント。



 a| 
 a| 
|  


| コントローラ  a| 
ONTAP
 a| 
ONTAPオペレーティングシステムを実行し、バックエンドストレージアレイと通信するストレージシステムのコンポーネント。コントローラはヘッドまたはCPUモジュールとも呼ばれます。



 a| 
| Hitachi、HP EVA、HP XP  a| 
ターゲットポートが配置されているストレージアレイ上のハードウェア。



 a| 
ノード
 a| 
3-PAR
 a| 
ホストの接続先ポートを含むストレージアレイ上のハードウェアコンポーネント。



 a| 
FEBEボード
 a| 
EMC Symmetrix
 a| 



| ストレージプロセッサ（SP）  a| 
EMC CX、EMC VNX
 a| 



 a| 
LUN
 a| 
多数のストレージアレイ
 a| 
1つ以上のディスクまたはディスクパーティションを、1つのスパンのディスクストレージスペースにグループ化すること。ONTAPのドキュメントでは、これを_array LUN_と呼んでいます。



 a| 
LDEV
 a| 
Hitachi、HP XP
 a| 



| LUN  a| 
ONTAP
 a| 
ONTAPシステムでは、接続されたストレージを仮想化し、そのストレージを（たとえばiSCSIやFC経由で）外部のアプリケーションやクライアントにLUNとして提供できます。クライアントは、フロントエンドLUNがどこに格納されているかを認識しません。



 a| 
LUN、仮想ディスク
 a| 
HP EVA
 a| 
仮想ディスク（ユーザインターフェイスでは_vDisk_と呼ばれます）は、ディスクグループ内に作成されるシミュレートされたディスクドライブです。仮想ディスクには、名前、冗長性レベル、サイズなどの特性の組み合わせを割り当てることができます。仮想ディスクを提供すると、そのストレージがホストに提供されます。



 a| 
アレイLUN
 a| 
ONTAPのドキュメント、ONTAPストレージ管理ツール
 a| 
ONTAPのドキュメントでは、ストレージアレイ上のLUNをフロントエンドLUN（ONTAP LUN）と区別するために_array LUN_という用語を使用しています。



 a| 
VLUN
 a| 
3PAR
 a| 
（volume-LUN）仮想ボリュームとLogical Unit Number（LUN；論理ユニット番号）のペアリング。ホストが仮想ボリュームを認識できるようにするには、ストレージアレイでvLUNを作成して、ボリュームをLUNとしてエクスポートする必要があります。



 a| 
 a| 
|  


| ボリューム  a| 
ONTAP
 a| 
サポートされている1つ以上のプロトコルでアクセス可能なユーザデータを格納する論理エンティティONTAP。サポートされているプロトコルには、ネットワークファイルシステム（NFS）、Common Internet File System（CIFS）、ハイパーテキスト転送プロトコル（HTTP）、ファイバチャネル（FC）、インターネットSCSI（iSCSI）などがあります。



 a| 
仮想ボリューム
 a| 
3PAR
 a| 
1つ以上の論理ディスクからデータをマッピングして作成される仮想ストレージユニット。

|===