---
permalink: implement-third-party/concept_requirements_for_formatting_array_luns.html 
sidebar: sidebar 
keywords: requirements, formatting, array, luns 
summary: さまざまな種類のアレイLUNフォーマットを実行できます。いずれのタイプも、LUNまたはストレージアレイ全体の可用性に影響します。 
---
= アレイLUNのフォーマットに関する要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
さまざまな種類のアレイLUNフォーマットを実行できます。いずれのタイプも、LUNまたはストレージアレイ全体の可用性に影響します。

新しいLUNをONTAPシステムにすぐに提供する必要がある場合は、クイックフォーマットを使用してください。LUNをあとでONTAPシステムに提供する予定の場合は、クイックフォーマットを推奨しますが、オンラインフォーマットも使用できます。

クイックフォーマットを使用することを推奨します。オンラインフォーマットとオフラインフォーマットのどちらも、次のリストで説明するように、LUNのフォーマットが完了するまでディスクの検出に時間がかかります。

* オンラインフォーマットでは、フォーマット中のアレイLUNは完全にオフラインになり、アレイLUNはSCSIコマンドに応答しません。
+
すべてのアレイLUNがフォーマットされるまで、一度に1つのアレイLUNでフォーマットが実行されます。

* オフラインフォーマットでは、ストレージアレイ全体がオフラインになり、ストレージアレイはSCSIコマンドに応答しません。
+
フォーマットが完了するまで、コントローラごとに一度に6つのアレイLUNがフォーマットされます。

+
ストレージアレイは、すべてのフォーマットが完了するまで応答しません。

* ONTAPシステムの初期セットアップ後にアレイLUNを作成する場合（任意のホスト）、オフラインフォーマットを使用すると、システムがパニック状態になります。
+
ルートボリュームのアレイLUNなど、ONTAPシステムにマッピングされたアレイLUNがある場合、それらのアレイLUNはフォーマットが完了するまで使用できなくなります。

* 他のホストのLUNのオンラインフォーマットおよびクイックフォーマットは、ONTAPシステムには影響しません。

